import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDwcP3hjm
akmtLLCKwmJTgBAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIOC8i1uljI/SITLH
EPNNvA7TPjUHII0TDVWtTG8y2IqfAAAAkGzv3qk6DSticD80Ac0BXKUhrZySYw7xDc5WXo
nftHP6Gtnqj3+M1L13sKWwIgb0o8rscX1HZDCnvmqbXaqPmXAqNw+QTLSaX2BPAnwEVOZs
XHyxFJAnylN92dQVdaNeKTkabExSp4GvzhcelZ7pUMesPVWCS89GmusGQsUeA21KEQmTNg
6klTnWutJL8cMQiA==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
